### ISSUE TITLE
Update #173 breaks lobby

### ISSUE THREAD

**Issue by samvinanzi** [Crackdown-PD2/BigLobby3#11]
Hi!
Following the very last Payday 2 update (#173 released on 01/03/2018), BigLobby3 seems to prevent other players to join a lobby. I'm opening this issue to discover if it is a common problem and, in case, to be sure the creators are aware of it.

Thanks!

**Comment by MrTipson** [comment]
Yep same. The most i was able to do with my friend is get on the loading screen of the lobby but it never ended.

**Comment by samvinanzi** [comment]
After installing the latest version of this mod, my friends crash when joining my lobbies.

**Comment by Iamgoofball** [comment]
Are they up to date?

**Comment by samvinanzi** [comment]
Yes, updated this evening

**Comment by Iamgoofball** [comment]
@steam-test1 going to give you maintainer access in a bit, check your email

**Comment by MrTipson** [comment]
Yep, same. Crashing. Name appears in lobby but then crashes.

Mon Mar 05 15:18:53 2018


Application has crashed: C++ exception
[string "lib/network/base/clientnetworksession.lua"]:52: attempt to index local 'sender' (a number value)



SCRIPT STACK

on_join_request_reply() @mods/BigLobby3-master/lua/lib/network/base/_clientnetworksession.lua:29
@mods/BigLobby3-master/lua/lib/network/base/handlers/_connectionnetworkhandler.lua:17


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name

**Comment by MrTipson** [comment]
Has anyone been able to track down the cause of this issue?

**Comment by Shad0wlife** [comment]
Did any of the commits from beginning of march actually fix this?

**Comment by Iamgoofball** [comment]
This is going to not get updated until after Spring Break.

**Comment by Nickxsch** [comment]
Has this been fixed? 'Cause we get stuck on "Joining game" each time we try...

**Comment by secondfry** [comment]
We can get 4 players in lobby, but any player joining any slot after fourth is dependent on luck it seems.
Rehosting seems to temporally fix the issue, yet we can't see their player models and they they never get to the game. They can't join after game started too.

**Comment by Iamgoofball** [comment]
I'm going to look into fixing up biglobby soon.

**Comment by Shad0wlife** [comment]
Secondfry's example sounds somewhat like my experience in #10 - as soon as too many players are in, some part of the connection breaks.
I'll try to reproduce this, but I rarely ever find enough people to assist in testing and I don't have enough pcs nor payday2s myself to do it alone.
