### ISSUE TITLE
Extra bots break stealth

### ISSUE THREAD

**Issue by Shad0wlife** [Crackdown-PD2/BigLobby3#16]
During the stealth part of missions, if there's more bots than idle positions on the map, the bots will walk around the map and usually jump through closed windows, breaking them and raising the alarm.

For lack of extra idle positions, could it be possible to restrain the extra bots from walking around in stealth in a different manner?

Also, the amount of bots is not affected by the max bots option at all. The only way to limit the game to x bots is to set the max lobby size to 
size =  n players + x bots

**Comment by Iamgoofball** [comment]
this is concerning

i'll look into it soonish

**Comment by Shad0wlife** [comment]
The fix definitely works, thanks. (Tested this monts ago, so I hope it still does)

Just remembered to write this here: If i get around to it I'll continue trying to bind the release of the bots to the alarm event - I already tried once at some point, but it didn't work. Mind you - if I get that working, fancy mission design where missions go silent again (if that ever happens, maybe in some mod - don't know) would probably have to be handled manually anyways.
