### ISSUE TITLE
Weapon select for bots

### ISSUE THREAD

**Issue by ThiagoCururu** [Crackdown-PD2/BigLobby3#18]
I can modify equipment for up to 3 bots, but I can't find an option to modify it for the remaining 13 bots I usually play with. Any ideas? Thanks for the amazing mod, it is so much fun to command an army like that :D

**Comment by steam-test1** [comment]
Due to how it's setup you have to create 5 panels for each extra character and manually adjust the positions for each extra panels

**Comment by VillainousV** [comment]
> Due to how it's setup you have to create 5 panels for each extra character and manually adjust the positions for each extra panel

Is this something we can do through notepad or as users?

**Comment by steam-test1** [comment]
It would be incompatible with Bot Weapons and Equipment mod
Maybe ask the creator to add more slots to crew management
