### ISSUE TITLE
wolfhud  vs big lobby  game crash on lo

### ISSUE THREAD

**Issue by repoman728** [Crackdown-PD2/BigLobby3#21]
Hi 
I have this problem during load . game is crashing ,    I know is wolfhud  but  when I delete big lobby , it is ok  Could you help me with that , please

Mon Nov 26 00:51:46 2018

Application has crashed: C++ exception
mods/WolfHUD/lua/CustomHUD.lua:4149: attempt to call method 'update' (a nil value)

SCRIPT STACK

update() lib/setups/gamesetup.lua:715
update() lib/setups/networkgamesetup.lua:21
orig__update() core/lib/setups/coresetup.lua:540
trainer/tools/pubinfloopv2.lua:141

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

**Comment by Jacky10X** [comment]
Where do you download the Wolfhud? is it from Github?

**Comment by repoman728** [comment]
pleae update

**Comment by Jacky10X** [comment]
try to remove all of your mod including your superBLT and reinstall the latest superblt and your mods (just backup your mods but not the whole mods folder and try it)

**Comment by repoman728** [comment]
ok thanks will do that
