### ISSUE TITLE
Crash in host when player enter in the lobby OR in-game

### ISSUE THREAD

**Issue by demydemise** [Crackdown-PD2/BigLobby3#29]
Here que crashlog:

Current thread: Main
Script stack:
                        send()  lib/network/base/networkpeer.lua:1066               
                        send()  @mods/BigLobby3-Master/lua/lib/network/base/_networkpeer.lua:14  
    on_join_request_received()  @mods/BigLobby3-Master/lua/lib/network/base/session_states/_hoststateingame.lua:157  
    on_join_request_received()  lib/network/base/hostnetworksession.lua:55          
                                lib/network/base/handlers/connectionnetworkhandler.lua:50

**Comment by steam-test1** [comment]
This should be fixed with version 3.2.2 of SuperBLT hook
