### ISSUE TITLE
"Auto Stop in Stealth" conflict with WolfHud V3.2.1

### ISSUE THREAD

**Issue by kumflargin** [Crackdown-PD2/BigLobby3#34]
There is an issue with WolfHud 3.2.1 and the "Automatically Stop All Bots In Stealth" option.  While this is enabled, heists (Stealth and Loud) would crash out after a few seconds of starting.  Easy to replicate with any heist that starts the crew in Casing Mode (Stealth or Loud), as the crash would happen right when the AI would mask up.  Disabling this option resolves this issue, and manually binding keys to the "Stop All Bots" and "Release All Bots" functions works as a substitute for stopping bots in stealth.  Disabling WolfHud also resolves the issue.

func() @mods/BigLobby3-master/lua/lib/managers/group_ai_states/_groupaistatebase.lua:23
whisper_mode() @mods/base/req/core/Hooks.lua:268
clbk() @mods/WolfHUD-master/lua/CustomHUD.lua:2222
call_listeners() @mods/WolfHUD-master/lua/CustomHUD.lua:473
set_condition() @mods/WolfHUD-master/lua/CustomHUD.lua:532
set_ai_stopped() @mods/WolfHUD-master/lua/CustomHUD.lua:4273
set_should_stay() lib/units/player_team/teamaimovement.lua:348

[crash.txt](https://github.com/Crackdown-PD2/BigLobby3/files/5470275/crash.txt)

**Comment by steam-test1** [comment]
Fixed in the latest auto update
