### ISSUE TITLE
Crash when playing solo

### ISSUE THREAD

**Issue by jovonkos** [Crackdown-PD2/BigLobby3#36]
If I'm joining a public game, it will load just fine.
Playing solo with bots will crash the game, however.

Here's the crash log for reference:
[crash.txt](https://github.com/Crackdown-PD2/BigLobby3/files/5537763/crash.txt)

Thank you for making this mod~

**Comment by steam-test1** [comment]
Will look into it

**Comment by steam-test1** [comment]
Fixed
